import os
import json
import glob
import re
import pandas as pd
from include.logic.helper import TARGET_COLUMNS


def aggregate_results_for_streamlit(
    results_dir: str, imputed_dir: str, output_csv_path: str
):
    """
    Crawls the metrics and timing JSONs, extracts parameters from the tags,
    and squashes them into a flat CSV for the Streamlit dashboard.
    """
    print("Aggregating results for Streamlit dashboard...")

    # Find all metric files generated by the evaluation phase
    metric_files = glob.glob(os.path.join(results_dir, "*_*_metrics.json"))

    data = []
    for mf in metric_files:
        filename = os.path.basename(mf)

        # Extract model and tag (e.g., "timesnet_r0.2_s5_metrics.json")
        match = re.match(r"([a-zA-Z0-9]+)_(.*)_metrics\.json", filename)
        if not match:
            continue

        model = match.group(1).upper()
        tag = match.group(2)

        # 1. Parse the Gap Ratio and Size from the tag
        if tag == "static":
            ratio = 0.0
            size = 0
        else:
            tag_match = re.search(r"r(\d+(?:\.\d+)?)_s(\d+)", tag)
            if tag_match:
                ratio = float(tag_match.group(1))
                size = int(tag_match.group(2))
            else:
                ratio = None
                size = None

        # 2. Fetch the corresponding Latency/Timing data (Inference Only)
        timing_file = os.path.join(imputed_dir, f"{model.lower()}_{tag}_timing.json")
        latency = None
        if os.path.exists(timing_file):
            with open(timing_file, "r") as tf:
                timing = json.load(tf)

                total_time = timing.get("total_algorithmic_time", 0.0)
                train_time = timing.get("train_time_seconds", 0.0)

                # Isolate pure inference time (safety bound to 1ms to prevent negatives/zeros)
                latency = max(0.001, total_time - train_time)

        # 3. Fetch the Accuracy Metrics
        with open(mf, "r") as f:
            metrics = json.load(f)

        # 4. Flatten the data column by column
        for col in TARGET_COLUMNS:
            if col in metrics and isinstance(metrics[col], dict):
                col_metrics = metrics[col]
                data.append(
                    {
                        "Model": model,
                        "Scenario_Tag": tag,
                        "Gap_Ratio": ratio,
                        "Gap_Size": size,
                        "Latency_Seconds": latency,
                        "Target_Column": col,
                        "RMSE": col_metrics.get("RMSE"),
                        "MAPE": col_metrics.get("MAPE"),
                    }
                )

    if not data:
        print("No metrics found to aggregate.")
        return

    # Build DataFrame and export
    df = pd.DataFrame(data)

    # Create the directory if it doesn't exist
    os.makedirs(os.path.dirname(output_csv_path), exist_ok=True)
    df.to_csv(output_csv_path, index=False)

    print(
        f"Successfully aggregated {len(df)} rows into Streamlit master dataset at: {output_csv_path}"
    )
    return output_csv_path
